language: python
python:
   - "2.7"
env:
   - DJANGO=1.7 DB=sqlite

install:
   - pip install -q Django==$DJANGO --use-mirrors
   - pip install djangorestframework

script:
   - python manage.py test api